[#configuration]
= Configuration

:idprefix: configuration_
:cpp: C++

The library does not require building or any special configuration to be used. However, there are a few options that can be enabled by defining macros prior to including library headers. These macros are summarized in the following table.

[%autowidth]
|===
|Macro |Description

|`BOOST_UUID_NO_SIMD`
|If defined, disables any optimizations for http://en.wikipedia.org/wiki/SIMD[SIMD]-enabled processors. Generic versions of algorithms will be used instead. This may result in suboptimal performance. By default, optimized algorithms are used, when the library is able to detect the availability of SIMD extensions at compile time.


|`BOOST_UUID_USE_SSE2`
|If defined, enables optimizations for http://en.wikipedia.org/wiki/SSE2[SSE2] exstensions available in modern x86 processors.

|`BOOST_UUID_USE_SSE3`
|If defined, enables optimizations for http://en.wikipedia.org/wiki/SSE3[SSE3] exstensions available in modern x86 processors.

|`BOOST_UUID_USE_SSE41`
|If defined, enables optimizations for http://en.wikipedia.org/wiki/SSE4#SSE4.1[SSE4.1] exstensions available in modern x86 processors.

|===

By default the library attempts to detect the availability of SIMD extensions in the target CPU at compile time and automatically defines the appropriate macros if succeeded. The `BOOST_UUID_USE_SSE*` macros can be defined by users, if auto-detection fails and it is known that the target CPU will have the extension. Do not enable these extensions unless you're certain that they will always be available on any machine that will run your program. The library performs no run time checks, so if an extension is missing, the program will likely crash. Note that enabling more advanced extensions implies that more basic ones are also available.
