[#name_generator_sha1]
== <boost/uuid/{zwsp}name_generator_sha1.hpp>

:idprefix: name_generator_sha1_

=== Synopsis

[source,c++]
----
#include <boost/uuid/namespaces.hpp>

namespace boost {
namespace uuids {

class name_generator_sha1
{
public:

    typedef uuid result_type;

    explicit name_generator_sha1( uuid const& namespace_uuid ) noexcept;

    uuid operator()( char const* name ) const noexcept;
    uuid operator()( wchar_t const* name ) const noexcept;

    template<class Ch, class Traits, class Alloc>
      uuid operator()( std::basic_string<Ch, Traits, Alloc> const& name ) const noexcept;

    uuid operator()( void const* buffer, std::size_t byte_count ) const noexcept;
};

}} //namespace boost::uuids
----

=== name_generator_sha1

The class `name_generator_sha1` generates name-based version 5 UUIDs (using SHA1 as the hashing algorithm.)

```
explicit name_generator_sha1( uuid const& namespace_uuid );
```

Effects: :: Constructs a `name_generator_sha1` that uses `namespace_uuid` as the namespace.

```
uuid operator()( char const* name ) const;
```

Returns: :: A name-based UUID version 5 produced from a digest of the namespace passed to the constructor and the characters of the string `name`, treated as octets.

Example: ::
+
```
using namespace boost::uuids;

name_generator_sha1 gen( ns::dns() );

uuid udoc = gen( "boost.org" );

std::cout << "\"boost.org\" UUID in DNS namespace, SHA1 version: " << udoc << std::endl;

// Output:
//   "boost.org" UUID in DNS namespace, SHA1 version: 0043f363-bbb4-5369-840a-322df6ec1926
```

```
uuid operator()( wchar_t const* name ) const;
```

Returns: :: A name-based UUID version 5 produced from a digest of the namespace passed to the constructor and the string `name`, converted to octets formed from a little-endian serialization of the characters of `name` converted to `uint32_t`.

Example: ::
+
```
using namespace boost::uuids;

name_generator_sha1 gen( ns::dns() );

uuid udoc = gen( L"boost.org" );

std::cout << "L\"boost.org\" UUID in DNS namespace, SHA1 version: " << udoc << std::endl;

// Output:
//   L"boost.org" UUID in DNS namespace, SHA1 version: c31c5016-3493-5dc2-8484-5813d495cc18
```

```
template<class Ch, class Traits, class Alloc>
  uuid operator()( std::basic_string<Ch, Traits, Alloc> const& name ) const;
```

Requires: :: `Ch` must be either `char` or `wchar_t`.

Returns: :: As if `operator()( name.c_str() )`.

```
uuid operator()( void const* buffer, std::size_t byte_count ) const;
```

Returns: :: A name-based UUID version 5 produced from a digest of the namespace passed to the constructor and the `byte_count` octets starting from `buffer`.
