[#uuid]
== <boost/uuid/uuid.hpp>

:idprefix: uuid_

=== Synopsis

[source,c++]
----
namespace boost {
namespace uuids {

class uuid {
public:

    // data

    std::uint8_t data[ 16 ];

    // iteration

    using value_type = std::uint8_t;
    using reference = std::uint8_t&;
    using const_reference = std::uint8_t const&;
    using iterator = std::uint8_t*;
    using const_iterator = std::uint8_t const*;
    using size_type = std::size_t;
    using difference_type = std::ptrdiff_t;

    iterator begin() noexcept;
    iterator end() noexcept;

    const_iterator begin() const noexcept;
    const_iterator end() const noexcept;

    // size

    constexpr size_type size() const noexcept;
    static constexpr size_type static_size() noexcept;

    // is_nil

    bool is_nil() const noexcept;

    // variant

    enum variant_type {
        variant_ncs, // NCS backward compatibility
        variant_rfc_4122, // defined in RFC 4122 document
        variant_microsoft, // Microsoft Corporation backward compatibility
        variant_future // future definition
    };

    variant_type variant() const noexcept;

    // version

    enum version_type {
        version_unknown = -1,
        version_time_based = 1,
        version_dce_security = 2,
        version_name_based_md5 = 3,
        version_random_number_based = 4,
        version_name_based_sha1 = 5
    };

    version_type version() const noexcept;

    // time-based fields

    using timestamp_type = std::uint64_t;
    using clock_seq_type = std::uint16_t;
    using node_type = std::array<std::uint8_t, 6>;

    timestamp_type timestamp_v1() const noexcept;
    uuid_clock::time_point time_point_v1() const noexcept;

    clock_seq_type clock_seq() const noexcept;
    node_type node_identifier() const noexcept;

    // swap

    void swap( uuid& rhs ) noexcept;
};

// operators

bool operator==( uuid const& lhs, uuid const& rhs ) noexcept;
bool operator!=( uuid const& lhs, uuid const& rhs ) noexcept;

bool operator<( uuid const& lhs, uuid const& rhs ) noexcept;
bool operator>( uuid const& lhs, uuid const& rhs ) noexcept;
bool operator<=( uuid const& lhs, uuid const& rhs ) noexcept;
bool operator>=( uuid const& lhs, uuid const& rhs ) noexcept;

std::strong_ordering operator<=>( uuid const& lhs, uuid const& rhs ) noexcept;

// free swap

void swap( uuid& lhs, uuid& rhs ) noexcept;

// hash_value

std::size_t hash_value( uuid const& u ) noexcept;

}} // namespace boost::uuids

// Boost.Serialization support

BOOST_CLASS_IMPLEMENTATION(boost::uuids::uuid, boost::serialization::primitive_type)

// std::hash support

template<> struct std::hash<boost::uuids::uuid>;
----

=== Iteration

Both constant and mutable iterators are provided.

```cpp
iterator begin() noexcept;
const_iterator begin() const noexcept;
```

Returns: :: `data + 0`.

```cpp
iterator end() noexcept;
const_iterator end() const noexcept;
```

Returns: :: `data + 16`.

Example: ::
+
```cpp
using namespace boost::uuids;

uuid u;

for( uuid::const_iterator it = u.begin(); it != u.end(); ++it )
{
    uuid::value_type v = *it;
    // do something with the octet v
}

for( uuid::iterator it = u.begin(); it != u.end(); ++it )
{
    *it = 0;
}
```

=== Size

The size of a `uuid` (in octets) is fixed at 16.

```cpp
constexpr size_type size() const noexcept;
```
```
static constexpr size_type static_size() noexcept;
```

Returns: :: `16`.

Example: ::
+
```cpp
using namespace boost::uuids;

uuid u;

assert( u.size() == 16 );
static_assert( uuid::static_size() == 16 );
```

=== is_nil

```cpp
bool is_nil() const noexcept;
```

Returns: :: `true` when the `uuid` is equal to the nil UUID, `{00000000-0000-0000-0000-000000000000}`, otherwise `false`.

=== Variant

Three bits of a `uuid` determine the variant.

```cpp
variant_type variant() const noexcept;
```

Returns: :: The UUID variant; usually `variant_rfc_4122` for non-nil UUIDs.

=== Version

Four bits of a `uuid` determine the version, that is the mechanism used to generate the `uuid`.

```cpp
version_type version() const noexcept;
```

Returns: :: The UUID version.

=== Time-based Fields

```cpp
timestamp_type timestamp_v1() const noexcept;
```

Returns: :: The UUIDv1 timestamp (number of 100ns intervals since 00:00:00.00, 15 October 1582).
  The value is only meaningful for version 1 UUIDs.

```cpp
uuid_clock::time_point time_point_v1() const noexcept;
```

Returns: :: The timestamp of a version 1 UUID, expressed as a `<chrono>` `time_point`.

```cpp
clock_seq_type clock_seq() const noexcept;
```

Returns: :: The clock sequence of a time-based UUID.
  The value is only meaningful for time-based UUIDs (version 1 and version 6).

```cpp
node_type node_identifier() const noexcept;
```

Returns: :: The node identifier of a time-based UUID.
  The value is only meaningful for time-based UUIDs (version 1 and version 6).

=== Swap

```cpp
void swap( uuid& rhs ) noexcept;
```

Effects: :: Exchanges the values of `*this` and `rhs`.

=== Operators

```cpp
bool operator==( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: As if `std::memcmp( lhs.data, rhs.data, 16 ) == 0`.

```cpp
bool operator!=( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: `!(lhs == rhs)`.

```cpp
bool operator<( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: As if `std::memcmp( lhs.data, rhs.data, 16 ) < 0`.

```cpp
bool operator>( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: `rhs < lhs`.

```cpp
bool operator<=( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: `!(rhs < lhs)`.

```cpp
bool operator>=( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: `!(lhs < rhs)`.

```cpp
std::strong_ordering operator<=>( uuid const& lhs, uuid const& rhs ) noexcept;
```

Returns: :: As if `std::memcmp( lhs.data, rhs.data, 16 ) \<\=> 0`.

=== Free Swap

```cpp
void swap( uuid& lhs, uuid& rhs ) noexcept;
```

Effects: :: `lhs.swap( rhs );`

=== hash_value

This function allows instances of `uuid` to be used with https://www.boost.org/doc/libs/release/libs/container_hash/doc/html/hash.html#ref_boostcontainer_hashhash_hpp[boost::hash].

```cpp
std::size_t hash_value( uuid const& u ) noexcept;
```

Returns: :: The hash value of the `uuid`.

Example: ::
+
```cpp
boost::unordered_flat_map<boost::uuids::uuid, int> hash_map;
```

=== Serialization

```cpp
BOOST_CLASS_IMPLEMENTATION(boost::uuids::uuid, boost::serialization::primitive_type)
```

`uuid` is serialized as a primitive type, that is, by its string representation.

=== std::hash

This specialization allows instances of `uuid` to be used with `std::hash`.

```cpp
template<> struct std::hash<boost::uuids::uuid>
{
    std::size_t operator()( boost::uuids::uuid const& v ) const noexcept;
}
```

```cpp
std::size_t operator()( boost::uuids::uuid const& v ) const noexcept;
```

Returns: :: `boost::uuids::hash_value( v )`.

Example: ::
+
```cpp
std::unordered_map<boost::uuids::uuid, int> hash_map;
```
