codecov:
  disable_default_path_fixes: true

fixes:
  - home/travis/build/*/boost-root/boost/libs/*/::
      
coverage:
  range: "85...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
