# Copyright 2016 Peter Dimov
# Copyright 2017 James E. King, III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

#
# Generic Travis CI build script for boostorg repositories
#
# Instructions for customizing this script for your library:
# 
# 1. Copy the ci/ directory from the same source into your project:
#    ci/build.sh runs the build
#    ci/coverity.sh is used to run a coverity build and upload results coverity scan
#    ci/codecov.sh is used to run a profiling build and upload results to codecov.io
# 2. Customize the compilers and language levels you want.  Default is C++03.
# 3. Update the global B2 environment settings to your liking.
# 4. If you have more than include/, src/, and test/ directories then
#    add them to the depinst.py line as "--include tools" for tools/ (you
#    can put multiple --include on the command line).
# 5. If you want to enable Coverity Scan, you need to provide the environment
#    variables COVERITY_SCAN_TOKEN and COVERITY_SCAN_NOTIFICATION_EMAIL.  
# 6. Enable pull request builds in your boostorg/<library> account.
#
# That's it - the script will do everything else for you.

sudo: false
dist: trusty
language: cpp

env:
  global:
  # see: http://www.boost.org/build/doc/html/bbv2/overview/invocation.html#bbv2.overview.invocation.properties
  # to use the default for a given environment, comment it out; recommend you build debug and release however..
  # - B2_ADDRESS_MODEL=address-model=64,32
  # - B2_LINK=link=shared,static
  # - B2_THREADING=threading=multi,single
    - B2_VARIANT=variant=release,debug

install:
  - export SELF=`basename $TRAVIS_BUILD_DIR`
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update -q --init tools/boostdep
  - git submodule update -q --init tools/build
  - git submodule update -q --init tools/inspect
  - cp -r $TRAVIS_BUILD_DIR/* libs/$SELF
  - export BOOST_ROOT="`pwd`"
  - export PATH="`pwd`":$PATH 
  - python tools/boostdep/depinst/depinst.py $SELF
  - ./bootstrap.sh
  - ./b2 headers

addons:
  apt:
    packages:
      - binutils-gold
      - gdb
      - libc6-dbg
        
branches:
  only:
    - develop
    - master
    
script:
  - cd libs/$SELF
  - ci/build.sh

jobs:
  include:
    #################### Jobs to run on every pull request ####################
    - os: linux
      env: 
        - COMMENT="C++03"
        - TOOLSET=gcc,gcc-7,clang
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      env: 
        - COMMENT="C++11"
        - TOOLSET=gcc,gcc-7,clang
        - CXXSTD=11
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      env: 
        - COMMENT=valgrind
        - TOOLSET=clang 
        - B2_VARIANT=variant=debug
        - DEFINES="define=BOOST_UUID_LIMITED_BENCH"
        - TESTFLAGS=testing.launcher=valgrind
      addons:
        apt:
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - valgrind
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test

  # cppcheck in trusty is VERY old (1.6.2) but acceptable for this project
    - os: linux
      env:
        - COMMENT=cppcheck
      addons:
        apt:
          packages:
            - cppcheck
      script:
        - cppcheck -I. --std=c++03 --enable=all --error-exitcode=1 --quiet --force libs/$SELF

    - os: linux
      env:
        - COMMENT=UBSAN
        - B2_VARIANT=variant=debug
        - TOOLSET=gcc-7
        - CXXFLAGS="cxxflags=-fno-omit-frame-pointer cxxflags=-fsanitize=undefined"
        - DEFINES="define=BOOST_UUID_LIMITED_BENCH"
        - LINKFLAGS=linkflags=-fsanitize=undefined
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: 
        - COMMENT=CodeCov
        - DEFINES="define=BOOST_UUID_LIMITED_BENCH"
        - TOOLSET=gcc-7
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - lcov
          sources:
            - ubuntu-toolchain-r-test
      script:
        - cd libs/$SELF
        - ci/codecov.sh

  # osx is disabled because it is very slow to start (can delay builds by 30 minutes)
  # - os: osx
  #   osx_image: xcode9
  #   env:
  #     - TOOLSET=clang
  #     - CXXSTD=03,11

    #################### Jobs to run on master merges only ###################
 
    # Coverity Scan
    - os: linux
      if: branch = master
      env:
        - COMMENT="Coverity Scan"
        - TOOLSET=gcc
      script:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
        - cd libs/$SELF
        - ci/coverity.sh

notifications:
  email:
    false

