# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false
dist: trusty

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - develop
    - master

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++03

    - os: linux
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.6
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++14
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++14
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      compiler: g++-7
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++17
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: clang++-5.0
      env: TOOLSET=clang COMPILER=clang++-5.0 CXXSTD=c++17
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boostdep
  - git submodule update --init tools/build
  - git submodule update --init tools/inspect
  - cp -r $TRAVIS_BUILD_DIR/* libs/uuid
  - python tools/boostdep/depinst/depinst.py uuid
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - ./b2 libs/uuid/test toolset=$TOOLSET

notifications:
  email:
    on_success: always
