# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - develop
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-12.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ADDPATH: C:\cygwin\bin;
      TOOLSET: gcc
      CXXFLAGS: cxxflags=-std=c++03
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ADDPATH: C:\cygwin\bin;
      TOOLSET: gcc
      CXXFLAGS: cxxflags=-std=c++11
# mingw disabled because boost::serialization won't build in mingw
# see: https://svn.boost.org/trac10/ticket/12205
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      ADDPATH: C:\mingw\bin;
#      TOOLSET: gcc
#      CXXFLAGS: cxxflags=-std=c++03
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      ADDPATH: C:\mingw\bin;
#      TOOLSET: gcc
#      CXXFLAGS: cxxflags=-std=c++11
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
#      TOOLSET: gcc
#      CXXFLAGS: cxxflags=-std=c++03
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
#      TOOLSET: gcc
#      CXXFLAGS: cxxflags=-std=c++11

install:
  - cd ..
  - git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boostdep
  - git submodule update --init tools/build
  - git submodule update --init tools/inspect
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\uuid
  - python tools/boostdep/depinst/depinst.py uuid
  - cmd /c bootstrap
  - b2 headers

build: off

test_script:
  - PATH=%ADDPATH%%PATH%
  - b2 libs/uuid/test toolset=%TOOLSET% %CXXFLAGS%
