# Copyright 2016, 2017 Peter Dimov
# Copyright (C) 2017, 2018 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - develop
    - master

matrix:
  allow_failures:
    - MAYFAIL: true

environment:
  global:
    # see: http://www.boost.org/build/doc/html/bbv2/overview/invocation.html#bbv2.overview.invocation.properties
    # to use the default for a given environment, comment it out; recommend you build debug and release however..
    # on Windows it is important to exercise all the possibilities, especially shared vs static
    # B2_ADDRESS_MODEL: address-model=64,32
    # B2_LINK: link=shared,static
    # B2_THREADING: threading=multi,single
    B2_VARIANT: variant=release,debug
    CXXSTD: 03

  matrix:
    - FLAVOR: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64,32
    - FLAVOR: Visual Studio 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0
      B2_ADDRESS_MODEL: address-model=64,32
    - FLAVOR: Visual Studio 2010, 2012, 2013
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-10.0,msvc-11.0,msvc-12.0
    - FLAVOR: cygwin (32-bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ADDPATH: C:\cygwin\bin;
      B2_ADDRESS_MODEL: address-model=32
      # https://github.com/boostorg/test/issues/144
      DEFINES: define=_POSIX_C_SOURCE=200112L
      THREADING: threadapi=pthread
      TOOLSET: gcc
    - FLAVOR: cygwin (64-bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ADDPATH: C:\cygwin64\bin;
      B2_ADDRESS_MODEL: address-model=64
      # https://github.com/boostorg/test/issues/144
      DEFINES: define=_POSIX_C_SOURCE=200112L
      THREADING: threadapi=pthread
      TOOLSET: gcc
    - FLAVOR:  mingw32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH:    i686
      B2_ADDRESS_MODEL: address-model=32
      SCRIPT:  ci\appveyor\mingw.bat
    - FLAVOR:  mingw64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH:    x86_64
      B2_ADDRESS_MODEL: address-model=64
      SCRIPT:  ci\appveyor\mingw.bat

install:
  - set SELF=%APPVEYOR_PROJECT_NAME:-=_%
  - git clone https://github.com/jeking3/boost-ci.git C:\boost-ci
  - xcopy /s /e /q /i C:\boost-ci\ci .\ci
  - ci\appveyor\install.bat

build: off

test_script:
  - set SELF=%APPVEYOR_PROJECT_NAME:-=_%
  - PATH=%ADDPATH%%PATH%
  - IF DEFINED SCRIPT (call libs\%SELF%\%SCRIPT%) ELSE (b2 libs/%SELF% toolset=%TOOLSET% cxxstd=%CXXSTD% %CXXFLAGS% %DEFINES% %THREADING% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)

